[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "xarm_ws"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.bash"]

[activation.env]
LD_PRELOAD = "/usr/lib/x86_64-linux-gnu/libGL.so.1"
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"
FASTDDS_BUILTIN_TRANSPORTS = "UDPv4"
# FASTDDS_DEFAULT_PROFILES_FILE = "/xarm_ws/config/fastrtps_udp.xml"
__NV_PRIME_RENDER_OFFLOAD = "1"
__NV_PRIME_RENDER_OFFLOAD_PROVIDER = "NVIDIA-G0"
__GLX_VENDOR_LIBRARY_NAME = "nvidia"
__VK_LAYER_NV_optimus = "NVIDIA_only"
ROS_DOMAIN_ID = "37"

# [feature.test.dependencies]
# pytest = "*"

# [environments]
# default = ["test"]

[tasks]
build = "colcon build"
clean = "rm -rf build/ install/ log/"
view_frames = "ros2 run tf2_tools view_frames"
launch_arms = "ros2 launch xarm_moveit_config dual_xarm7_moveit_realmove.launch.py"
apriltag_launch = "ros2 launch apriltag_ros apriltag_femto_std.launch.py"
workspace_origin_broadcaster = "python3 workspace_origin_broadcaster.py"

#MTC
launch_mtc = "ros2 launch bimanual_laptop_mtc execute_laptop_task.launch.py"
run_close = "ros2 action send_goal /execute_laptop_task bimanual_laptop_msgs/action/ExecuteLaptopTask '{task_name: close_single, use_bimanual: false, lid_angle_goal_deg: 15.0, world_frame: workspace_world, laptop_frame_hint: laptop_nominal}'"

[dependencies]
#Core ROS2 packages
setuptools = "*"
wheel = "*"
python = ">=3.12.13,<3.13"
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-rmw-implementation = ">=2.15.6,<3"
colcon-common-extensions = ">=0.3.0,<0.4"

#Build Tools
cmake = ">=4.3.4,<5"
make = ">=4.4.1,<5"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.11.0,<2"
ninja = ">=1.13.2,<2"
git = ">=2.54.0,<3"

#Moveit2
ros-jazzy-moveit = ">=2.12.4,<3"
ros-jazzy-moveit-resources = ">=3.1.0,<4"
ros-jazzy-moveit-task-constructor-core = ">=0.1.3,<0.2"
ros-jazzy-moveit-task-constructor-msgs = ">=0.1.3,<0.2"
ros-jazzy-moveit-task-constructor-capabilities = ">=0.1.3,<0.2"

#ros2_control
ros-jazzy-ros2controlcli = ">=4.45.1,<5"
ros-jazzy-controller-manager = ">=4.45.1,<5"
ros-jazzy-joint-trajectory-controller = ">=4.40.0,<5"
ros-jazzy-joint-state-broadcaster = ">=4.40.0,<5"
ros-jazzy-ros2-control = ">=4.45.1,<5"
ros-jazzy-ros2-controllers = ">=4.40.0,<5"
ros-jazzy-ros-testing = ">=0.6.0,<0.7"

#Gazebo Harmonic
ros-jazzy-ros-gz = ">=1.0.22,<2"
ros-jazzy-gz-ros2-control = ">=1.2.18,<2"
ros-jazzy-ros-gz-sim = ">=1.0.22,<2"
ros-jazzy-ros-gz-bridge = ">=1.0.22,<2"

#Rviz2
ros-jazzy-rviz2 = ">=14.1.20,<15"

#xArm specifics
ros-jazzy-xacro = ">=2.1.1,<3"
ros-jazzy-joint-state-publisher = ">=2.4.1,<3"
ros-jazzy-joint-state-publisher-gui = ">=2.4.1,<3"
ros-jazzy-robot-state-publisher = ">=3.3.3,<4"
filelock = ">=3.29.4,<4"

#Camera packages
ros-jazzy-image-transport = ">=5.1.7,<6"
ros-jazzy-image-transport-plugins = ">=4.0.7,<5"
ros-jazzy-compressed-image-transport = ">=4.0.7,<5"
ros-jazzy-image-publisher = ">=5.0.11,<6"
ros-jazzy-camera-info-manager = ">=5.1.7,<6"
ros-jazzy-diagnostic-updater = ">=4.2.7,<5"
ros-jazzy-diagnostic-msgs = ">=5.3.7,<6"
ros-jazzy-statistics-msgs = ">=2.0.3,<3"
ros-jazzy-backward-ros = ">=1.0.8,<2"
ros-jazzy-orbbec-camera = ">=1.5.13,<2"
ros-jazzy-orbbec-description = ">=1.5.13,<2"
# ros-jazzy-apriltag-ros = "*"

#Ament
ros-jazzy-ament-cmake = ">=2.5.6,<3"
ros-jazzy-ament-cmake-core = ">=2.5.6,<3"
ros-jazzy-ament-cmake-ros = ">=0.12.0,<0.13"
ros-jazzy-rosidl-default-generators = ">=1.6.0,<2"
ros-jazzy-rosidl-default-runtime = ">=1.6.0,<2"

#Geometry and TF
ros-jazzy-tf2 = ">=0.36.20,<0.37"
ros-jazzy-tf2-ros = ">=0.36.20,<0.37"
ros-jazzy-tf2-geometry-msgs = ">=0.36.20,<0.37"
ros-jazzy-geometry-msgs = ">=5.3.7,<6"
ros-jazzy-shape-msgs = ">=5.3.7,<6"
ros-jazzy-std-msgs = ">=5.3.7,<6"
ros-jazzy-rclcpp = ">=28.1.18,<29"
ros-jazzy-rclcpp-action = ">=28.1.18,<29"
ros-jazzy-action-msgs = ">=2.0.3,<3"
ros-jazzy-launch = ">=3.4.10,<4"
ros-jazzy-launch-ros = ">=0.26.11,<0.27"
ros-jazzy-tf-transformations = ">=1.1.1,<2"
