apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.028
    max_hamming: 0
    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    pose_estimation_method: "pnp"
    tag_ids:    [2, 3, 4, 5, 21]
    tag_frames: ["tag_2", "tag_3", "tag_4", "tag_5", "tag_21"]
    tag_sizes:  [0.028, 0.028, 0.028, 0.028, 0.019]